name: tests status

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: requirements install
        run: |
          cd $GITHUB_WORKSPACE
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests 
        run: python -m unittest tests
               
  sending_message:
        runs-on: ubuntu-latest
        needs: [test]

        steps:
          - name: "Telegram Notification, when test is successed"
            uses: "appleboy/telegram-action@master"
            if: ${{ success() }}
            with:
              to: ${{ secrets.TZ2_CHATID }}
              token: ${{ secrets.TZ2_TOKEN }}
              args: Все ок
          - name: "When tests are failed"
            uses: appleboy/telegram-action@master
            if: ${{ failure() }}
            with:
              to: ${{ secrets.TZ2_CHAT_ID }}
              token: ${{ secrets.TZ2_TOKEN }}
              message: "возникла проблема: ${{ steps.tests.outputs.stderr }}"
